version: '3.8'
services:
  db:
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meln_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - melnichanka
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meln_db"]
      interval: 10s
      timeout: 1s
      retries: 5

  nginx:
    image: nginx:stable-alpine3.17-slim
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static/
    ports:
      - "80:80"
    networks:
      - melnichanka

  web:
    image: ghcr.io/kroshkabyte/melnichanka:v0.1.0
    env_file: .env
    ports:
      - "8000:8000"
    command: sh entrypoint.sh
    networks:
      - melnichanka
    volumes:
      - static_volume:/app/static/
    depends_on:
      db:
        condition: service_healthy

networks:
  melnichanka:

volumes:
  static_volume:
  postgres_data:
